create table activity_categories (
                                     id bigint generated by default as identity,
                                     name text not null unique,
                                     primary key (id)
);