create table activities (
                            id bigint generated by default as identity,
                            category_id bigint not null,
                            name text not null unique,
                            primary key (id)
);