create table activity_requests (
                                   id bigint generated by default as identity,
                                   participants_required integer not null,
                                   activity_id bigint not null,
                                   address text,
                                   coordinates geography(POINT,4326),
                                   join_deadline timestamp,
                                   activity_start timestamp,
                                   comment text,
                                   status smallint not null,
                                   creator_id bigint not null,
                                   primary key (id)
);