create table users (
                       id bigint generated by default as identity,
                       rating numeric(38,2) not null,
                       email text not null unique,
                       info text,
                       name text,
                       nickname text not null unique,
                       password text not null,
                       phone text unique,
                       role smallint not null,
                       primary key (id)
);